### ISSUE TITLE
Edit recipe no longer working on Windows

### ISSUE THREAD

**Issue by Smolders2007** [nextcloud/cookbook#1290] opened 2022-10-26 07:42 UTC
**Description**
The edit function no longer shows the entire recipe, so no longer functional.

**Reproduction**
1. Go toany recipe
2. Click on Edit
3. Scroll down no longer works

**Expected behavior**

**Actual behavior**
Please describe in clear statements what is happening in reality.

**Screenshots**

**Browser**
Google Chrome

**Versions**
Nextcloud server version: ??
Cookbook version: 25.0.0
Database system: MySQL/MariaDB/PostgreSQL/Sqlite

**Comment by seyfeb** [comment] 2022-10-26 08:05
I assume that you are using Nextcloud 25.0.0, since there is no Cookbook version 25.0.0. Currently the Cookbook app is not compatible with NC 25, but we're working on it, see #1208 . Closing this, if the issue is a different one, we may reopen.

**Closed by seyfeb** 2022-10-26 08:05 UTC
Labels: bug
