### ISSUE TITLE
Error in Log:  Unexpected end tag : div in Entity

### ISSUE THREAD

**Issue by rafny** [nextcloud/cookbook#440] opened 2020-12-16 15:30 UTC
I just noticed this error in my logs appear - not sure if it's because of NC20 or not, but it's basically running a few times a second.

The app seems to function fine. I can import and edit recipes without an issue.

```json
{
    "reqId": "x5rgiKGRkAl01arENF0Y",
    "level": 3,
    "time": "2020-12-16T15:21:48+00:00",
    "remoteAddr": "IP_ADDRESS",
    "user": "UserName",
    "app": "PHP",
    "method": "POST",
    "url": "/index.php/apps/cookbook/import",
    "message": {
        "Exception": "Error",
        "Message": "DOMDocument::loadHTML(): Unexpected end tag : div in Entity, line: 6646 at /var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php#424",
        "Code": 0,
        "Trace": [
            { "function": "onError", "class": "OC\\Log\\ErrorHandler", "type": "::" },
            { "file": "/var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php", "line": 424, "function": "loadHTML", "class": "DOMDocument", "type": "->" },
            { "file": "/var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php", "line": 754, "function": "parseRecipeHtml", "class": "OCA\\Cookbook\\Service\\RecipeService", "type": "->" },
            { "file": "/var/www/nextcloud/apps/cookbook/lib/Controller/MainController.php", "line": 223, "function": "downloadRecipe", "class": "OCA\\Cookbook\\Service\\RecipeService", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php", "line": 169, "function": "import", "class": "OCA\\Cookbook\\Controller\\MainController", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php", "line": 100, "function": "executeController", "class": "OC\\AppFramework\\Http\\Dispatcher", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/AppFramework/App.php", "line": 152, "function": "dispatch", "class": "OC\\AppFramework\\Http\\Dispatcher", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/Route/Router.php", "line": 308, "function": "main", "class": "OC\\AppFramework\\App", "type": "::" },
            { "file": "/var/www/nextcloud/lib/base.php", "line": 1008, "function": "match", "class": "OC\\Route\\Router", "type": "->" },
            { "file": "/var/www/nextcloud/index.php", "line": 37, "function": "handleRequest", "class": "OC", "type": "::" }
        ],
        "File": "/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
        "Line": 91,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0",
    "version": "20.0.3.2",
    "id": "5fda261eb639e"
}
```
Running v0.7.7 of Cookbook app

**Comment by christianlupus** [comment] 2020-12-21 10:27
Hello. Is this always the same message you get?
From the error message, it seems that during parsing/importing a recipe there was an issue with parsing the HTML code. What recipe URL did you try to import?

**Comment by rafny** [comment] 2020-12-21 14:05
Some recent recipes, not sure exactly which might have caused the error:
- https://www.rebelrecipes.com/spiced-black-beans-turmeric-roast-cauliflower/
- https://www.simplyrecipes.com/recipes/butternut_squash_and_black_bean_skillet_dinner/
- https://www.foodnetwork.com/recipes/butternut-squash-and-bean-soup-recipe-1956134

I get the error above, and occasionaly this one too:

```json
{
    "reqId": "x5rgiKGRkAl01arENF0Y",
    "level": 3,
    "time": "2020-12-16T15:21:48+00:00",
    "remoteAddr": "IP_ADDRESS",
    "user": "UserName",
    "app": "PHP",
    "method": "POST",
    "url": "/index.php/apps/cookbook/import",
    "message": {
        "Exception": "Error",
        "Message": "DOMDocument::loadHTML(): Tag use invalid in Entity, line: 6554 at /var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php#424",
        "Code": 0,
        "Trace": [
            { "function": "onError", "class": "OC\\Log\\ErrorHandler", "type": "::" },
            { "file": "/var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php", "line": 424, "function": "loadHTML", "class": "DOMDocument", "type": "->" },
            { "file": "/var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php", "line": 754, "function": "parseRecipeHtml", "class": "OCA\\Cookbook\\Service\\RecipeService", "type": "->" },
            { "file": "/var/www/nextcloud/apps/cookbook/lib/Controller/MainController.php", "line": 223, "function": "downloadRecipe", "class": "OCA\\Cookbook\\Service\\RecipeService", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php", "line": 169, "function": "import", "class": "OCA\\Cookbook\\Controller\\MainController", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php", "line": 100, "function": "executeController", "class": "OC\\AppFramework\\Http\\Dispatcher", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/AppFramework/App.php", "line": 152, "function": "dispatch", "class": "OC\\AppFramework\\Http\\Dispatcher", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/Route/Router.php", "line": 308, "function": "main", "class": "OC\\AppFramework\\App", "type": "::" },
            { "file": "/var/www/nextcloud/lib/base.php", "line": 1008, "function": "match", "class": "OC\\Route\\Router", "type": "->" },
            { "file": "/var/www/nextcloud/index.php", "line": 37, "function": "handleRequest", "class": "OC", "type": "::" }
        ],
        "File": "/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
        "Line": 91,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0",
    "version": "20.0.3.2",
    "id": "5fe0ab3b3a47d"
}
```

**Comment by rafny** [comment] 2020-12-21 14:13
I just noticed that the errors do actually have variety in the line number reference:
![image](https://user-images.githubusercontent.com/49330216/102785885-a9d88380-436c-11eb-9083-6c70274749bd.png)

**Comment by christianlupus** [comment] 2020-12-22 08:05
I just saw that the errors are from a few days ago. I assume these errors are showing only during import sessions. The named location and stack trace points toward a function that is used solely for importing. If this is true, the issue was triggered during an import.

All the named pages have some invalid HTML in them. You can check using [an HTML validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.foodnetwork.com%2Frecipes%2Fbutternut-squash-and-bean-soup-recipe-1956134). The parsing of the HTML is comparably strict and therefore all errors are reported in such a way as this issue is about.

The real solution is to make the website owners aware of the fact that they have errors in their sites and should correct them. Everything else is just hoping for the best.

As we cannot do anything about their faulty sites, I will close the issue here. If the error persists not only during imports but regular usage, the problem is somewhere else. In this case, I will happily reopen the issue.

**Closed by christianlupus** 2020-12-22 08:05 UTC
