### ISSUE TITLE
No entries for utensils, ingredients and preparation.

### ISSUE THREAD

**Issue by chrisbonn** [nextcloud/cookbook#471] opened 2021-01-05 16:04 UTC
**Description**
When creating a new recipe, it is no longer possible in the current version (0.7.7) to make entries in the utensils, ingredients and preparation. The version 0.7.6 did not have this problem.

**Reproduction**
1. Go to 'New recipe.'
2. Click on 'utensils, ingredients and preparation'
4. No entries possible

**Expected behavior**
It should be possible to specify utensils, preparation and ingredients in a new recipe.

**Screenshots**
I think a screenshot is not necessary

**Browser**
Firefox/Safari

**Comment by seyfeb** [comment] 2021-01-05 16:07
Duplicate of #430
You could either try either the linked version in the issue or try out the current development version where this is already fixed (but is not published to the NC app store, yet).

**Comment by christianlupus** [comment] 2021-01-09 18:48
The issue is solved in the current v0.7.8. Closing here. If not solved, please comment, then we can reopen.

**Closed by christianlupus** 2021-01-09 18:48 UTC
Labels: bug
