### ISSUE TITLE
Cannot create Recipes

### ISSUE THREAD

**Issue by Kiolali** [nextcloud/cookbook#469] opened 2021-01-02 13:49 UTC
**Description**
Creating a new recipe via Browser (Chrome, Firefox) doesn't work. After filling out the input fields, clicking on the checkmark results in an endless loading spinner. The developer console shows many type errors (e.g. "vue.runtime.esm.js:1888 TypeError: Cannot set property 'prepTime' of null").

**Reproduction**
1. Go to cookbook app
2. Click on "Create recipe"
3. Click on checkmark

**Expected behavior**
Saving the recipe.

**Screenshots**
![image](https://user-images.githubusercontent.com/16179562/103458560-a4365280-4d09-11eb-8a43-7ee150a8b66c.png)

![cookbook_spinner](https://user-images.githubusercontent.com/16179562/103458528-5faab700-4d09-11eb-8ec8-b3d19089fdd4.gif)

**Browser**
Chrome (87, Windows), Firefox (83, Linux)

**Comment by seyfeb** [comment] 2021-01-02 13:55
This is probably a duplicate of #430 or #438

**Comment by christianlupus** [comment] 2021-01-02 17:05
This is solved by #386.

**Closed by christianlupus** 2021-01-02 17:05 UTC
Labels: bug

**Comment by Kiolali** [comment] 2021-01-02 17:22
Thanks! It works with the current master branch.
