### ISSUE TITLE
References don't work and make all text containing a slash / to be treated as a reference

### ISSUE THREAD

**Issue by agamez** [nextcloud/cookbook#645] opened 2021-03-05 11:23 UTC
On version 0.8.3, having ingredients lists such as "1/2 kg of tomatoes", now appears as "1undefined2kg of tomatoes".

Entering a properly formatted reference as, for example, #r/2540402 (real ID of a recipe of mine) results in the recipe viewer as appearing 
`"<a class="recipe-reference-inline" href="undefinednextcloudundefinedindex.phpundefinedappsundefinedcookbookundefined#undefinedrecipeundefined2540402">#2540402<undefineda> "`

Also, the popup with the list of references appears not only when writing #, but also when entering a 3 in which # character is located too (but not with the numeric keyboard).

Main problem, however, is it treating every / occurance as a reference to undefined, as this is breaking already existing functionality.

**Comment by seyfeb** [comment] 2021-03-05 12:25
To make sure I understand you correctly: Whenever you press the button for entering a '3', the recipe-selection pop-up opens? 

Otherwise duplicate of #641

**Comment by agamez** [comment] 2021-03-05 12:29
That is correct. Typing a 3 (key above 'e') launches the pop-up. Typing a 3 (on the numeric keyboard above '.' and to the left of Intro) does not launch the pop-up.

**Comment by christianlupus** [comment] 2021-03-06 15:55
This is due to the check for keycode in [the EditInputField.vue file](https://github.com/nextcloud/cookbook/blob/415106f4025ce9b7e02cc87f6f16339a449976d9/src/components/EditInputField.vue#L73).

I am not sure if the keycode approach is so well suited. The hash has only keycode 51  on the US keyboard. Other layouts have the hash on different keys with different keycodes. On the German (for example) it is 163, while 51 is 3/§.
Wouldn't it be more feasible to let the browser type the symbol and later check the textual representation of the lastly typed glyph?

**Comment by seyfeb** [comment] 2021-03-06 16:45
I see! This should definitely be changed to work on any keyboard layout.

**Comment by seyfeb** [comment] 2021-03-07 13:55
This can be closed if #648 and #642 solved the problems.

**Comment by christianlupus** [comment] 2021-03-13 18:34
I am closing here as the PRs should have taken care of the issue.

If the problem still persists, we can reopen.

**Closed by christianlupus** 2021-03-13 18:34 UTC
Labels: bug
