### ISSUE TITLE
Can not search for recipe or tags

### ISSUE THREAD

**Issue by ringogalga** [nextcloud/cookbook#360] opened 2020-10-28 12:37 UTC
Me and all my friends are useing this cookbook with diffrent browsers.
All of us can not search a recipe or filter by a tag
So the tags are useless
And why can I give a recipe only one category?
Is that what you want?

**Comment by seyfeb** [comment] 2020-10-28 20:22
Hello @ringogalga 

For the search/tags question, you might want to check out #318, #330.

Regarding the category, check out #277.

Basically: It is worked upon the search functionality while instead of multiple categories, tags may be used.

**Comment by christianlupus** [comment] 2020-10-31 08:48
As this seems to be basically a duplicate of different other issues/PRs, I will close it here. If new aspects arise, we can of course reopen the topic.

**Closed by christianlupus** 2020-10-31 08:48 UTC
Labels: bug
