### ISSUE TITLE
Native Android/iOS app

### ISSUE THREAD

**Issue by jgubler** [nextcloud/cookbook#308] opened 2020-08-16 12:32 UTC
Is it in any way planned to have native iOS/Android apps for cookbook at some point?

I do understand that it is probably a lot of additional work to take on, and almost the same functionality is technically already accessible by logging into your Nextcloud instance in the browser. And it's also very understandable that this would be postponed due to limited resources.

However, ease of use is just really really important to get ones relatives to switch over to a shared cookbook app, particularly a self-hosted one. And let's be honest, the browser usage is just not as convenient as a native app when wanting to look up recipes while shopping groceries etc.
To highlight how this seemingly small UX barrier is perceived (particularly by non tech savvy people): it's currently preferable to just export all recipes to pdfs and put them in a nextcloud folder, because that way they can at least be accessed natively and offline, without having to login to anything.

I don't want this to come across as being ungrateful for this free app that people spend their free time on for me to enjoy, I think the web app is great and if I always had a desktop PC it would be fine, but unfortunately the phone is the main usage device for recipes.

**Comment by christianlupus** [comment] 2020-08-16 13:31
Duplicate of #207 

This issue is already under development. If you are willing to test out, @Teifun2 might be able to send you links where you can test a beta version. He asked recently for beta testers.

**Closed by christianlupus** 2020-08-16 13:31 UTC
Labels: enhancement
