### ISSUE TITLE
Bulk Download Feature

### ISSUE THREAD

**Issue by terencedesu** [nextcloud/cookbook#529] opened 2021-01-18 03:52 UTC
It would be great if it would be possible to download all recipes into a single PDF file (basically either a single PDF or separate PDF files of each recipe like a print preview). This would allow giving cookbooks to others without Nextcloud or a human readable backup in case one's nextcloud is offline for a while.

**Comment by christianlupus** [comment] 2021-01-18 12:56
Duplicate of #316

**Closed by christianlupus** 2021-01-18 12:56 UTC
Labels: enhancement
