### ISSUE TITLE
Make recipes public

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/cookbook#289] opened 2020-07-23 11:25 UTC
It would be nice if I could make some recipes public and give the link to my friends

**Comment by Dellyjoe** [comment] 2020-08-05 12:31
Also would like to ask if we can make the recipes shareable between people on Nextcloud.

**Comment by mrzapp** [comment] 2020-08-11 08:04
Closing as duplicate of #120

**Closed by mrzapp** 2020-08-11 08:04 UTC
Labels: enhancement
