### ISSUE TITLE
Javascript error 

### ISSUE THREAD

**Issue by Rhobil** [nextcloud/cookbook#445] opened 2020-12-20 13:35 UTC
**Description**
1. Some cookbook functions do not work.
Add tool/ Add incredient / add instructions
2. Can not save new recipes.

**Reproduction**

Problem 1 (add):
1. Go to a new recipe
2. Click on add tool / add incredient / add instructions
4. See error (javascript error/ nothing happens)

Problem 2 (save):
1. Go to a new recipe
2. enter a name
3. click on save (checkmark)

**Expected behavior**
The functions of the buttons should be executed.

**Screenshots**

**Browser**
Chrome 87 / Firefox 84

** Versions*
Nextcloud: 20.0.4
Cookbook: 0.7.7

** Javascript errors ***
TypeError: Cannot read property 'recipeIngredient' of null
    at addNew (EditInputGroup.vue:32)
    at click (EditInputGroup.vue?37df:110)
    at Re (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2179)
    at HTMLButtonElement.s._wrapper (vue.runtime.esm.js:6917)

TypeError: Cannot read property 'recipeInstructions' of null
    at addNew (EditInputGroup.vue:32)
    at click (EditInputGroup.vue?37df:110)
    at Re (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2179)
    at HTMLButtonElement.s._wrapper (vue.runtime.esm.js:6917)

TypeError: Cannot read property 'tool' of null
    at addNew (EditInputGroup.vue:32)
    at click (EditInputGroup.vue?37df:110)
    at Re (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2179)
    at HTMLButtonElement.s._wrapper (vue.runtime.esm.js:6917)

On save:

TypeError: Cannot read property 'id' of null
    at a.save (RecipeEdit.vue:141)
    at a.<anonymous> (RecipeEdit.vue:211)
    at Re (vue.runtime.esm.js:1854)
    at a.e.$emit (vue.runtime.esm.js:3888)
    at a.saveChanges (AppControls.vue:211)
    at click (AppControls.vue?b7a6:130)
    at Re (vue.runtime.esm.js:1854)
    at a.n (vue.runtime.esm.js:2179)
    at a.execFirstAction (Breadcrumb.js:66)
    at Re (vue.runtime.esm.js:1854)

**Comment by seyfeb** [comment] 2020-12-20 14:30
Probably duplicate of #430. Have you tried the temporary solution [described here](https://github.com/nextcloud/cookbook/issues/430#issuecomment-744036064)?

**Comment by Rhobil** [comment] 2020-12-20 14:35
Yep duplicate, sry. I will try the solution, thanks!

**Closed** 2020-12-20 14:35 UTC
Labels: bug
