### ISSUE TITLE
Cannot create new recipe since the last update

### ISSUE THREAD

**Issue by webnar** [nextcloud/cookbook#481] opened 2021-01-08 12:37 UTC
**Description**
Cannot create a new recipe (won't save) since the last update. Also cannot add Tools, Ingredients and instructions when is push add new it does not provide a new field (only with new recipes). I can import a new recipe and adjust it completely through the URL add option.

**Reproduction**
1. new recipe
2. populate recipe
3. no Tools, ingredients or Instructions can be added (no field appears when pushing add)
4. New recipe will not save

**Expected behavior**
Saving the new recipe

**Browser**
In Chrome, IE and Firefox

**Comment by seyfeb** [comment] 2021-01-08 12:38
Duplicate of #430

**Closed** 2021-01-09 18:39 UTC
Labels: bug
