### ISSUE TITLE
Allow recipie calculation

### ISSUE THREAD

**Issue by tpawork** [nextcloud/cookbook#874] opened 2022-01-10 15:32 UTC
**Is your feature request related to a problem? Please describe.**
It's not possible to scale the recipie for different portions.

**Describe the solution you'd like**
Inrgedient should be split into amount, unit and name. currently its only a string.
Then it would be possible to make calculations for different portions.

(Also a ingredient database that can be filled manually and select in the recipie creator would be nice :)

**Comment by seyfeb** [comment] 2022-01-10 17:03
Duplicate of #116

**Closed by seyfeb** 2022-01-10 17:03 UTC
Labels: enhancement
