### ISSUE TITLE
The folder name should be auto trimmed if exceeding the character limit

### ISSUE THREAD

**Issue by peterge1998** [nextcloud/cookbook#1620] opened 2023-04-17 07:24 UTC
**Is your feature request related to a problem? Please describe.**
When you import a recipe with a name that is too long, the app becomes unavailable and produces an error when launching (#1616). This is a really frustrating experience for the user, it does not tell what is going wrong, why it does happen and how it can be prevented.

**Describe the solution you'd like**
Ask the user to enter a custom recipe name, which fits the current character limit of X or auto trim the folder name to sth with (...) at the end, so it does always fit the limit.

**Describe alternatives you've considered**
The auto replace is my favorite, because it leaves no option for misusing this anymore.

**Comment by seyfeb** [comment] 2023-10-21 17:11
Since the referenced issue is closed.. Is this still a problem? 
Does anybody know what is the maximum allowed folder length?

**Comment by christianlupus** [comment] 2023-10-23 04:46
Yes it is still an issue. 

The problem is that some sites misuse the title of the recipe to add some promotion. This results to literally hundreds of chars. Depending on the used file system this can get a problem.

Additionally, any special chars might also cause trouble (I think there was a similar and this related issue.)

**Comment by seyfeb** [comment] 2023-10-30 11:19
I did not find the/a related issue with special characters causing trouble in here, but I found some things:

- In the NC forum: [What are (un-)allowed characters for folders and files](https://help.nextcloud.com/t/what-are-un-allowed-characters-for-folders-and-files/58676)

- In the server PHP code [the constant `FILENAME_INVALID_CHARS`](https://github.com/nextcloud/server/blob/0299955074eb43c06d8779758934c72d4e845890/lib/public/Constants.php#L56)

- A Stackoverflow post comparing file systems [Allowed characters in filename](https://stackoverflow.com/questions/4814040/allowed-characters-in-filename)]

**Comment by christianlupus** [comment] 2024-01-04 07:25
We should additionally provide a visual flag in case a field gets too long inn the web ui. Something like a red backround/border or so. Nevertheless the backend needs fixing.

**Comment by christianlupus** [comment] 2024-05-21 17:18
This should be fixed with #1268

**Closed by christianlupus** 2024-05-21 17:18 UTC
Labels: bug, Backend
