### ISSUE TITLE
Compatibility with Nextcloud Version 20.0

### ISSUE THREAD

**Issue by atroxtartarus** [nextcloud/cookbook#331] opened 2020-10-06 11:56 UTC
After Upgrading to Nextcloud 20 the App is marked as untested App. It says "Server version 19 or lower is required.". An Update of the App for Nextcloud 20.0 is necessary.

**Comment by christianlupus** [comment] 2020-10-07 08:40
Have you tried if the app can be activated nevertheless? Are there any issues?

**Comment by christianlupus** [comment] 2020-10-07 08:42
PS: I just saw [this line](https://github.com/nextcloud/cookbook/blob/master/appinfo/info.xml#L17). So i t seams with the very next release, the issue should be gone.

**Comment by atroxtartarus** [comment] 2020-10-07 09:19
It seems like it is working without any problems if I activate it nevertheless

**Comment by christianlupus** [comment] 2020-10-09 18:05
I changed to 21 as this one is currently not compatible according to the app info. We need to test here.

**Comment by steeljm1** [comment] 2020-10-10 22:14
I can confirm that upgrading from 19.0.4 -> 20.0.0 the app is functional after enabling it i.e. view, create, and edit recipes. No warnings/errors in logs.

**Comment by christianlupus** [comment] 2020-10-11 08:56
OK, as there was some unclarity if this issue is related to 20 or 21, I reverted back to 20 and close this on as the app seems compatible with 20. Thanks for testing @steeljm1.

**Closed by christianlupus** 2020-10-11 08:56 UTC
Labels: enhancement

**Comment by obbardc** [comment] 2020-11-08 08:29
On the app page, it doesn't state compatibility with v20: https://apps.nextcloud.com/apps/cookbook

**Comment by christianlupus** [comment] 2020-11-08 08:38
Yes, as there was no release published since the v20 compatibility was set.

**Comment by matclou** [comment] 2020-11-16 21:59
Hello, I am running the app (0.7.6) on Nextcloud 20.0.1 and I am missing the search option in the right menu:

![grafik](https://user-images.githubusercontent.com/71438822/99313126-4fc13b80-285f-11eb-933c-494956ba31d7.png)

Is this issue related to V20?

**Comment by christianlupus** [comment] 2020-11-17 12:04
@matclou Unless this problem is purely related to V20 (aka working differently on NC V19), this is a separate issue.
Where do you expect the search to appear? On the release there is no search yet implemented. But maybe you are referring to something differently so I wanted to make sure. Especially because you are referring the **right** menu but showing a screenshot of the top left edge.

**Comment by matclou** [comment] 2020-11-17 17:28
Dear Christian, oh I did not no this. And indeed I meant the left menu and not the right menu!

As I am a beginner in using the cookbook app I took the screenshot visible at https://apps.nextcloud.com/apps/cookbook as granted: There is a search function implemented in the left menu.

So there is currently no search function integrated?

**Comment by christianlupus** [comment] 2020-11-17 19:43
@matclou This was replaced by another feature in #318. This is not yet published so it might take a bit of time. The search as depicted in the app store was removed a few releases ago as it was faulty.

**Comment by matclou** [comment] 2020-11-17 21:41
That is good to know - thanks for informing and your work! ;-)

**Comment by Obi-Wahn** [comment] 2020-11-21 16:38
Thanks for the app! I'm looking forward to a release with v20 compatibility!

**Comment by radoeka** [comment] 2020-11-28 14:25
> Thanks for the app! I'm looking forward to a release with v20 compatibility!

Is it possible to just release for NC-20.  NC-20 is now listed as general available (via the stable update channel).  It's likely that more people start to move to NC-20.  It would be nice to have Cookbook listed as compatible with NC-20.

**Comment by obbardc** [comment] 2020-11-28 14:49
For what it's worth, it installed on v20 and works just fine even though
Nextcloud said that it was untested.

Agree cutting a new release sounds ideal though.
