### ISSUE TITLE
Can't input nutritional information

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/cookbook#673] opened 2021-04-04 10:37 UTC
**Description**
I can open a drop down list with options like calories or fat content, but when I choose one of this options nothing happens.

**Reproduction**
1. Create a new / edit a recipe
2. Click on options of the nutritional information
3. Choose one option

**Expected behavior**
I would expect that I can choose an option like calories and input the amount of calories. Then choose the option for fat content and input this value also. And so on...

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1378907/113506002-66340f00-9542-11eb-9f5a-f20ec6a7e507.png)

**Browser**
FF 87

**Versions**
Nextcloud server version: 20.0.7
Cookbook version: 0.8.4

**Comment by seyfeb** [comment] 2021-04-06 15:22
Duplicate of #652

**Closed by seyfeb** 2021-04-06 15:22 UTC
Labels: bug
