### ISSUE TITLE
Calculate required ingredients quantities based on servings

### ISSUE THREAD

**Issue by Athesis** [nextcloud/cookbook#622] opened 2021-02-27 15:29 UTC
Currently there is no posibillity to automaticly recalculate the needed quantities based on the serving size. 

By having the quantety of each ingredient in an own textfield it would be easy to calculate other serving sizes based on an simple rule of three.

**Comment by christianlupus** [comment] 2021-02-27 18:47
Duplicate of #116

**Closed by christianlupus** 2021-02-27 18:47 UTC
Labels: enhancement
