### ISSUE TITLE
Cant veiw imported recipes 

### ISSUE THREAD

**Issue by critterskins** [nextcloud/cookbook#1221] opened 2022-09-22 21:40 UTC
Cannot view imported recipes on app works fine within nextcloud itself.

**Comment by critterskins** [comment] 2022-09-22 21:43
![Screenshot_20220922-143601](https://user-images.githubusercontent.com/22518657/191856661-9845ea33-4947-44f0-a983-0884978ca791.jpg)

**Comment by christianlupus** [comment] 2022-09-23 04:23
This issue is invalid for multiple reasons. 

- by far not all information are provided. I do not understand the problem. 
- the problem is related to a 3rd party mobile app.

Closing therefore.

**Closed** 2022-09-23 04:24 UTC

**Comment by critterskins** [comment] 2022-09-24 02:08
> 

Sorry I thought I was contacting the mobile app developer not the nextcloud app dev.

**Comment by christianlupus** [comment] 2022-09-25 21:36
I hope you find the appropriate developer soon.
