### ISSUE TITLE
RecipeView Nutrition Information interrupts viewing on iPads

### ISSUE THREAD

**Issue by gjpc** [nextcloud/cookbook#1078] opened 2022-07-09 04:05 UTC
**Is your feature request related to a problem? Please describe.**
When you view a recipe in the Cookbook on a standard size iPad, if Nutrition Information is present, it breaks up the flow of the recipe display. It appears between ingredients and instructions. This is because it is in the `<aside>` section of the **RecipeView.vue** file. You can see this happen in any browser by making the window less wide until the entire aside column is presented before the main section. See the image below.

**Describe the solution you'd like**
When the display gets too narrow, the Nutrition Information should drop below the instructions. 

**Describe alternatives you've considered**
Alternatively, the Nutrition Information should always appear below the Instructions. This avoids unnecessary scrolling when following the recipe on a kitchen based iPad.

![bad cookbook](https://user-images.githubusercontent.com/1188979/178090614-d0518bfa-98a7-4273-870b-54b3335f7ee5.JPG)

**Comment by christianlupus** [comment] 2022-07-24 16:01
This should be done with the PR merged. If the problem ist persistent with the next version, please report back.

**Closed by christianlupus** 2022-07-24 16:01 UTC
Labels: enhancement, Frontend

**Comment by gjpc** [comment] 2022-07-24 17:50
Thank you very much @christianlupus , I test as soon as the next version is released.

**Comment by christianlupus** [comment] 2022-07-24 18:30
If you want, you can continue with the steps as described here: https://nextcloud.github.io/cookbook/dev/use-autobuild

**Comment by gjpc** [comment] 2022-07-24 20:39
Hi @christianlupus 
Well I gave testing a try. I downloaded the cookbook-appstore artifact at [https://github.com/nextcloud/cookbook/actions/runs/2727757340]. After backing up my SQL and recipes directory I moved the release cookbook to safety and placed the new artifact cookbook into the nextcloud apps directory. I then restarted apache.

Unfortunately I got the following error when selecting the cookbook:

> Internal Server Error
> 
> The server was unable to complete your request.
> 
> If this happens again, please send the technical details below to the server administrator.
> 
> More details can be found in the server log.
> Technical details
> 
>     Remote Address: 148.64.106.30
>     Request ID: Qkrq43q1x6KTnVAkGlz7

The rather long log file lines seem to complain about the r.date_created column is not in the SQL table and a deadlock occurring. I attached the lines. 

I am not sure if I caused the problem, I am just very happy that my cookbook still works once I restored the original cookbook app.

[nextcloud cookbook fail log.txt](https://github.com/nextcloud/cookbook/files/9176635/nextcloud.cookbook.fail.log.txt)

**Comment by christianlupus** [comment] 2022-07-24 21:45
Ahh, yeah, sorry. There was a small change in the database structure recently. 

You would have to trigger an update of the app state. This can be done via disabling and reenabling the app on the settings or via `occ upgrade` as far as I know. The new columns should not lead to problems even if you revert back. 

As a side effect, the app should be faster. 😉

**Comment by gjpc** [comment] 2022-07-24 22:14
Outstanding solution @christianlupus! The recipe display even survives iPad rotation from landscape to portrait and back, always maintaining readability. The speed boost is terrific, blink and the the full recipe appears. Thanks for your thorough and quick resolution.

**Comment by christianlupus** [comment] 2022-07-25 05:44
> P.S. do you anticipate any problem when the update drops into circulation?

You mean the next release? There is always a certain risk involved. We try to be careful but of course we cannot test all possible installation situations. We try however to fix things within short time or even provide steps to revert things. Until now, the admin can simply remove the app and install an older version. After configuring and rescanning, the cookbook is built from scratch based on the files in the Nextcloud.

**Comment by gjpc** [comment] 2022-08-04 01:56
Hi @christianlupus  FYI the version of the cookbook I downloaded does not down load recipes from allrecepies.com I get an error box: **Cannot parse recipe: Unknown object found during flattening of instructions.** The old version parses the same recipes that failed. Here is one that works with the old version and not the new. https://www.allrecipes.com/recipe/272437/keto-smothered-chicken-thighs/
