### ISSUE TITLE
www.indianhealthyrecipes.com: No parser found for the given import.

### ISSUE THREAD

**Issue by Razzaline** [nextcloud/cookbook#1642] opened 2023-04-30 14:41 UTC
**Failing website:**
https://www.indianhealthyrecipes.com/chana-masala/

**Checking if valid metadata are present:**
- [x] Yes, I check the source code of the website and found metadata.

**Cookbook version:**
0.10.2

**Problem description (if applicable):**
The page cannot be imported. The error message is: "No parser found for the given import."

**Comment by christianlupus** [comment] 2023-05-16 16:00
Duplicate of #1675

**Closed by christianlupus** 2023-05-16 16:00 UTC
Labels: website support

**Comment by pachakam** [comment] 2024-09-23 03:12
Hello @Razzaline,

I noticed the issue with importing from pachakam.com. It seems you're encountering the error message "No parser found for the given import."

For the pages on [pachakam.com](https://pachakam.com/), it's important to ensure that valid metadata is present for successful imports. If there are any updates or further steps we can take to resolve this issue, please let us know. We appreciate your efforts in addressing this.

Thank you!
