### ISSUE TITLE
[Feature Request] Make the app ring when the cooking time is over

### ISSUE THREAD

**Issue by Thovi98** [nextcloud/cookbook#671] opened 2021-04-03 14:32 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cook and I begin the cooking time timer : when it’s over, only this popup appears
![2021-04-03 16_23_31-Livre de recettes - Nextcloud](https://user-images.githubusercontent.com/51749973/113481374-7fcd4c00-9499-11eb-8a3b-3abc19194b6b.jpg)

**Describe the solution you'd like**
I would like, if it’s possible, that the app rings when time is over. So I don’t have to be on my computer during the whole cooking process.

**Describe alternatives you've considered**
Use another alarm app on my phone, but I think an integrated alarm is better, because it’s what we think we will have when we press the timer button.

Thanks !

(Firefox, latest release ; Nextcloud 20.0.7 ; Cookbook 0.8.4)

**Comment by christianlupus** [comment] 2021-04-03 15:15
Just to be sure we are on the same page: You want the cookbook app within NC to emit a sound, right? We are not talking of any sort of mobile phone app, right?

**Comment by Thovi98** [comment] 2021-04-05 15:06
> You want the cookbook app within NC to emit a sound, right?

Yes please. Because there is now a timer but not sound when countdown is over. On the desktop with Firefox. Thanks.

**Comment by christianlupus** [comment] 2022-07-22 05:28
I will check. I think I have a bunch of sights with open source royalty free music samples maybe there is something that can be used as an alarm.

Regarding your question with the namespace is nextcloud or not nextcloud: in which location did you stumble over this? In the package description of the app there is the name with the term nextcloud. This is against best practice of the current app development guides. So far it did not hurt. It was introduced in the very beginning of the app and never touched as far as I know. 

If you are referring to something different, please explain where and what is the issue.

**Comment by MarcelRobitaille** [comment] 2022-07-22 05:44
Thanks for looking into the sound we could use.

I am not sure where it's coming from, but when using the `file-loader` webpack loader, the URL of the mp3 starts with `/apps/nextcloud-cookbook` but it should be `/apps/cookbook`. I noticed that `nextcloud-cookbook` shows up in `package.json` as the `name`, but I'm not exactly sure where webpack is pulling this from or why it's working for `.js` but not `.mp3` using `file-loader`.

Ok, I just tested it by modifying `package.json`. It is taking the `name` from the `package.json`. I think we can either update the name (we have to update `MainController.php` as well), see if there's a way to use `nextcloud-cookbook` inside of `apps` instead of just `cookbook` (at least it would be consistent), or leave the `.replace('nextcloud-cookbook', 'cookbook')`.

**Comment by MarcelRobitaille** [comment] 2022-07-26 22:03
The `file-loader` issue was fixed with #1099. The only thing left is to find a sound we can use I think.

**Comment by christianlupus** [comment] 2022-07-27 14:27
I have looked for some samples, that I found on the net. According to my understanding of [their FAQ](https://pixabay.com/service/faq/) and [their terms](https://pixabay.com/service/terms/), we are allowed to use these:

* [alarm clock short | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/alarm-clock-short-6402/)
* [Clock Alarm | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/clock-alarm-8761/)
* [Piano Logo | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/piano-logo-108963/)
* [harp-motif2 | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/harp-motif2-36586/)
* [Alarm clock ticking | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/alarm-clock-ticking-6069/)
* [mechanical alarm clock | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/mechanical-alarm-clock-14474/)
* [Grandfathers Clock -1 Ding Dong | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/grandfathers-clock-1-ding-dong-14356/)
* [service bell ring | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/service-bell-ring-14610/)
* [Magic mallet | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/magic-mallet-6262/)
* [Positive Massive Logo | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/positive-massive-logo-13624/)
* [Positive Logo Opener | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/positive-logo-opener-13622/)
* [WinFantasia | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/winfantasia-6912/)
* [doorbell2 | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/doorbell2-6450/)
* [Reception Bell | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/reception-bell-14620/)
* [success_bell | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/success-bell-6776/)
* [Bells 2 | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/bells-2-31725/)
* [Person Knocking | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/person-knocking-18474/)
* [telephone ring.wav | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/telephone-ringwav-14674/)
* [Dreamy bells | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/dreamy-bells-47721/)
* [Bell2 | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/bell2-15465/)
* [Bell1 | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/bell1-15464/)
* [Bell Ringing | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/bell-ringing-43862/)
* [062751_small bell.wav | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/062751-small-bellwav-45418/)
* [085932_Bell.wav | Royalty Free Music - Pixabay](https://pixabay.com/sound-effects/085932-bellwav-41750/)

There might be more and some of these might need cutting to have a single alarm instead of multiple dongs. This is just a selection of some sounds I would consider useful. Some are alarms while others are "notification" sounds that the clock is running.

How do we proceed? Just ask the community what they prefer? Selecting ourselves?

**Comment by seyfeb** [comment] 2022-07-27 15:41
Thanks for compiling the extensive list. We should first decide:  Should be repeated until confirmed (like a timer on a smartphone) or should it only be a short single tone or a short procession of tones which stop automatically after some time?

For a continued signal, I would consider those suitable from that list:

alarm clock short
service bell ring
success bell
small_bell
Bell 

For a short clip others might work as well.

**Comment by christianlupus** [comment] 2022-07-27 17:05
Personally, I am a person who needs a kick in the ass if I need to do something. So, I would prefer a continuous notification until I acknowledge it. But this might be unnerving as you might work in the kitchen and do not want to touch the display with dirty hands.

**Comment by seyfeb** [comment] 2022-07-27 17:39
There is always the possibility to add yet another user preference 😅

**Comment by MarcelRobitaille** [comment] 2022-07-28 06:45
Wow, those are good ones. Thanks for finding them. I was not able to find anything nearly that good. I like the alarm clock ones best. Should we do a vote or how should we proceed?

**Comment by christianlupus** [comment] 2022-07-28 07:03
I will prepare something for that.

**Comment by christianlupus** [comment] 2022-07-28 17:51
I put something in the poll #1125.

**Comment by christianlupus** [comment] 2022-08-20 20:30
Ok, the poll indicated a tendency towards a continuing alarm until confirmation.

When planned accordingly, it should be possible to short after one ring without confirmation by the user. The user night have an option to select his/get preferences in some sort of settings. 

Would you consider that manageable, @MarcelRobitaille?

Do we want to offer the user the option to select from multiple sounds? Or will we just offer one fixed sound?

The poll was not super active. I was hoping for more participants. Asking what sound might be best will most probably (in my opinion) lead to much answers. I think we will have to decide on one and see if the users are complaining.

I do not see anyone coming up with better sound samples for now. If there is still something to cover, please report back. I will think of a way to make a survey so we can internally see, what deems best to us. Okay?

**Comment by christianlupus** [comment] 2022-08-21 15:25
I created a survey on my own instance and published/shared it [here](https://nextcloud.christian-wolf.click/nextcloud/apps/polls/s/IGG5OvO4Hnl9hU3W). If you would like to participate, you are welcome to do so anonymously.

Ping @seyfeb @MarcelRobitaille

**Comment by christianlupus** [comment] 2022-08-24 06:38
Attention, I had the wrong link inserted in the last comment. I have updated it. I am sorry for the inconvience.

**Comment by seyfeb** [comment] 2022-08-24 18:59
It is probably a bit of an overkill, but thanks for creating the poll, anyway! :D

**Comment by MarcelRobitaille** [comment] 2022-10-14 09:59
Hi @christianlupus. Sorry I haven't been active here.

Here is what I understand so far:
1. The sound is https://pixabay.com/sound-effects/alarm-clock-short-6402/
1. By default, the alarm plays continuously until the user presses "OK" in the alert
1. The user can change to a single alarm instead of a continuous alarm in app settings

I am still not clear about a few things:
1. Where should these settings be? Maybe related to #1067?
2. Is it possible to select no alarm at all in the settings?

If this is cleared up, I think I can complete this fairly quickly.

**Comment by christianlupus** [comment] 2022-10-14 13:44
Hello, @MarcelRobitaille,

yes, we have mostly the same understanding so far.

No alarm makes no sense to me, to be honest. The user is not obligated to activate the alarm clock, so if he is doing it, he will also want to know when things are due. So, No 2 would be a _no_ for me.

I would prepare to allow the user to change the settings, but for now, we stick with a continuous sound. This will be the default setting.

Once #1067 is done, we can make the setting configurable and let the user store the setting in the DB/backend. The reason is that I'd like to avoid adding too much more options to the current settings and overflowing the user completely.

Does this clear out things?

**Closed** 2022-10-20 17:52 UTC
Labels: enhancement, javascript, Frontend
