### ISSUE TITLE
Split ingredients by processing types

### ISSUE THREAD

**Issue by made2140** [nextcloud/cookbook#292] opened 2020-08-08 11:49 UTC
**Is your feature request related to a problem? Please describe.**
Some recipes have not one, but usually two sections of ingredients (e.g. [this cake recipe](https://cookinglsl.com/chocolate-mascarpone-cheesecake-recipe/)).
Separate lists have a better visibility in terms of preparing beforehand. 

**Describe the solution you'd like**
It would be really nice to have an option to make several ingredients' lists, if there are that many in the recipe.

**Comment by Teifun2** [comment] 2020-08-08 15:20
Could you check if this is somehow possible while sitll following the https://schema.org/Recipe convention?

If it is not possible it will probably not be done, as there is no guarantee how such a recipe will be interpreted in the future!

**Comment by Eothred** [comment] 2020-08-11 05:56
Duplicate of #285 I believe?

**Comment by mrzapp** [comment] 2020-08-11 08:02
as @Eothred said, closing as a duplicate

**Closed by mrzapp** 2020-08-11 08:02 UTC
Labels: enhancement
