### ISSUE TITLE
all recipes from Serious Eass don't work

### ISSUE THREAD

**Issue by qq7te** [nextcloud/cookbook#1034] opened 2022-06-08 04:36 UTC
Hi, Serious Eats is my favorite food-related website, with tons of recipes.
Despite them having a schema.org recipe portion, already in jason-ld form in the source of the page, cookbook can't seem to parse the page.

I imagine it's one of those near-misses where the code is almost perfect, but there's one little thing preventing it from succeeding.
Here is a test recipe:
https://www.seriouseats.com/vegetable-qorma-5324131

Can cookbook be fixed?  Can I help in any way? I am not a php developer... :(

**Comment by christianlupus** [comment] 2022-06-08 05:53
In the current `master` branch, the problem is no longer reproducible. Most probably it was fixed in #553.

**Closed by christianlupus** 2022-06-08 05:53 UTC
Labels: website support

**Comment by qq7te** [comment] 2022-06-09 02:08
awesome !  Thank you and sorry for wasting your time!  Love the app!
