### ISSUE TITLE
Unhelpful error message `Unknown answer returned from server. See logs.` given if recipe name missing

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/cookbook#923] opened 2022-03-20 05:15 UTC
**Description**
When saving a recipe, the message `Unknown answer returned from server. See logs.` is shown if the name field is empty. Only the name field seems to be absolutely required. Adding `test` here allows the form to be submitted even if everything else is empty.

**Reproduction**
1. Click '+ Create Recipe'
2. Immediately click save
1. `Unknown answer returned from server. See logs.` is shown in a popup window

**Expected behavior**
There is a helpful message like `Title field is required`. This could even be shown inline. The input could get a red border and the text shown directly underneath.

**Actual behavior**
`Unknown answer returned from server. See logs.` is shown in a popup window

**Browser**
Firefox 97.0.1 on Linux

**Versions**
Nextcloud server version: Master branch
Cookbook version: Master branch (reproduced in my "production" instance running 0.9.10)

**Comment by christianlupus** [comment] 2022-05-02 09:19
As I wrote in the PR, this PR will not create a reb border or something in this direction. Currently, only the basic functionality to detect it and fetch the problem is introduced. For a more feature-rich frontend, please open a new issue of type feature request when the PR is merged. Thanks!

**Closed** 2022-05-10 18:34 UTC
Labels: bug

**Comment by faxotherapy** [comment] 2023-11-18 16:19
Hi, still have this issue. I imported receipe from Marmiton. Now, when I want to edit it, I got the following error message: “unknown answer return from server, see log”. That’s nice to tell me to see the log, but which logs (cookbook log or nextcloud log) and where to located the log. Thank you for your help.
