### ISSUE TITLE
Install / activation impossible on NC21

### ISSUE THREAD

**Issue by Florentin68** [nextcloud/cookbook#567] opened 2021-02-04 19:10 UTC
**Description**
Install / activation impossible on NC21.

**Reproduction**
1. Go to App store
2. Click on Install or activate if already installed
3. See error "There is no table with name 'nextcloud.oc_cookbook_recipes' in the schema."

**Expected behavior**
Plugin should initialize and activate itself

**Screenshots**
![image](https://user-images.githubusercontent.com/7725052/106942700-cc5c0b80-6724-11eb-9b0d-5f1b4d3e08a5.png)

**Browser**
Chrome Dev 90 on Ubuntu Linux 20.10

**Versions**
Nextcloud server version : 21RC1 (idem on 21 beta 8)
Cookbook version : 0.7.10

**Comment by christianlupus** [comment] 2021-02-04 19:38
The app is currently not compatible with NC21.

Duplicate of #341
Duplicate of #551
Related with #504

Was the app automatically installed? Could it be installed without a warning?
Could you please check your `config.php` to see if there is something mentioned in `aap_install_overwrite`?

**Comment by Florentin68** [comment] 2021-02-04 21:35
I tried to install it manually. I discovered this app when I already was running NC21. 
No warning during install. 

There is a list of 34 apps I've installed in the attribute you mention in my `config.php`:

```
  'app_install_overwrite' =>
  array (
    0 => 'files_downloadactivity',
    1 => 'apporder',
    2 => 'calendar',
    3 => 'deck',
    4 => 'keeweb',
    5 => 'files_markdown',
    6 => 'qownnotesapi',
    7 => 'ransomware_protection',
    8 => 'tasks',
    33 => 'cookbook',
    34 => 'bookmarks'
),
```

**Comment by christianlupus** [comment] 2021-02-05 11:34
Could you test the following:

1. Uninstall the app once more.
2. Remove the cookbook from `app_install_overwrite` (you might need to decrement all subsequent entries' ids like `bookmarks` above)
3. Check if you can still install the cookbook app.

The app is definitively not (yet) supported under NC 21 and will not work (as you have found out). NC 21 is not yet released so I suspect they disabled the app installation prevention (see `app_install_overwrite`) for the **beta** testers.

**Comment by languitar** [comment] 2021-02-21 17:55
Now that NC 21 is released (at least on dockerhub): is there any plan when support will be available?

**Comment by christianlupus** [comment] 2021-02-23 07:11
Yes, of course, there is work done to make the app compatible with NC 21. Currently, there are multiple things at hand and we are all volunteers. So, please be so kind and give us the time to get things straight.

For your reassurance: #605 is the first step in this direction. Let's see how far we can get in this PR. As soon as it is installable we might release a new version of the app.

**Comment by christianlupus** [comment] 2021-03-03 20:10
The new version 0.8.3 was just pushed out with support for NC 21.

**Closed by christianlupus** 2021-03-03 20:10 UTC
Labels: bug
