### ISSUE TITLE
Automatic calculate ingredient for different rations

### ISSUE THREAD

**Issue by Jim8Knopf** [nextcloud/cookbook#894] opened 2022-02-11 11:11 UTC
When I have an recipe it's static and when some friends come I have to calculate by my own.

In my opinion it would be easier if there is an number input for rations that calculates automatically the ingredient of the recipe

**Comment by seyfeb** [comment] 2022-02-16 01:50
Duplicate of #116

**Closed by seyfeb** 2022-02-16 01:50 UTC
Labels: enhancement
