### ISSUE TITLE
Can't add ingredients to new recipes after upgrading NC20

### ISSUE THREAD

**Issue by adriaaah** [nextcloud/cookbook#430] opened 2020-12-10 19:27 UTC
**Description**
Although I can import new recipes to Cookbook, new ones can't be added because 
- neither tools nor ingredients nor instructions can be added, because the '+Add' buttons don't react when clicked, and
- the Save button keeps spinning forever and the recipe can't be saved
- I've checked that I have Cookbook 0.7.7
- I've flushed NC cache
- In the browser console (Developer tools) the following error is spotted every time I try to add a new line: 

```
TypeError: this.$parent.recipe is null
    addNew EditInputGroup.vue:32
    click EditInputGroup.vue:110
    VueJS 3
vue.runtime.esm.js:1888:12
    VueJS 6
```
When I try to save it, I get
```
TypeError: this.recipe is null
    save RecipeEdit.vue:141
    mounted RecipeEdit.vue:211
    VueJS 2
    saveChanges AppControls.vue:211
    click AppControls.vue:130
    VueJS 2
    execFirstAction Breadcrumb.js:66
    VueJS 3
vue.runtime.esm.js:1888:12
```

**Reproduction**
Steps to reproduce the behaviour:
1. Go to 'Create recipe'
2. Click on '+Add' (no matter which one) -> no new line is displayed
3. Try to save a recipe (with just a name and a description) by clicking the check icon, which was replaced with a spinning wheel but it keeps "saving" and the recipe is not saved (can't be found in the expected NC directory)

**Expected behaviour**
- I expected that a new line was created when I clicked the '+Add' button
- I expected to save the recipe when I clicked the check icon

**Browser**
- Firefox 83 (w. private session)
- Chromium 89.0.4347.0 (w. incognito window)

**Comment by christianlupus** [comment] 2020-12-11 14:13
This should be solved in the current master branch. I cannot confirm the issue there but in the `stable` branch (that represents the app store's version. There seems to be a race in the current `master` (see [here](https://github.com/nextcloud/cookbook/issues/419#issuecomment-742362777)). As soon as these are ironed out, we can make a new release to solve the issue.

**Comment by Kieltux** [comment] 2020-12-12 18:17
I can confirm the problem with Cockbook 0.7.7 (here on Nextcloud 19.0.6)
Brower: Firefox 78.5.0 ESR, Opera 73.73.0.3856.257.
Since the update Cookbook 0.7.7
- I can not add a recipe (saving does not work)
- I can not add Tools
- I can not add Ingredients
- I can not add Instructions

Adding Tools, Ingredients or Instructions:

```
TypeError: this.$parent.recipe is null
    addNew EditInputGroup.vue:32
    click EditInputGroup.vue:110
    VueJS 3
```
Saving a recipe
```
TypeError: this.recipe is null
    save RecipeEdit.vue:141
    mounted RecipeEdit.vue:211
    VueJS 2
    saveChanges AppControls.vue:211
    click AppControls.vue:130
    VueJS 2
    execFirstAction Breadcrumb.js:66
    VueJS 3
```

**Comment by GambaJo** [comment] 2020-12-12 20:57
Same here
NC: 20.0.3
CB: 0.7.7

**Comment by RufioHugo** [comment] 2020-12-13 12:10
I've got the problem also - can't create a recipe!
Nextcloud 19.0.6 - Cockbook 0.7.7 ...

**Comment by radoeka** [comment] 2020-12-13 13:01
Same for me: NC: 20.0.3 + CB: 0.7.7

**Comment by christianlupus** [comment] 2020-12-13 16:55
For those willing to give the current dev version a try:

1. Make a backup ;)
2. Disable the cookbook app in the NC
3. Remove the cookbook folder from the NC apps installation path (either `apps` or `custom_apps`).
4. Replace it with the following contents: [cookbook.tar.gz](https://github.com/nextcloud/cookbook/files/5684986/cookbook.tar.gz)
5. Go to the app settings in NC. Reenable the app, but do not update to 0.7.7.

If an error happens, just disable the app once more, remove it manually and install it from the NC app store again.

**Comment by brononius** [comment] 2020-12-13 17:49
The dev version is working at first sight...

**Comment by Githopp192** [comment] 2020-12-14 16:48
same to me: NC 19.0.5, CB:0.7.7  - as soon i find some time i will try the DEV Version

**Comment by mggcodes** [comment] 2020-12-16 08:03
Hi Guys,
I have the same issue with Version 0.7.7 and NC 20.0.3
After the given Workaround I can add Utils and other things and can save it. But only the Name and the Category is saved.
Other inputs won't save.

**Comment by Githopp192** [comment] 2020-12-16 11:03
mggcodes  ... did you install CB:0.7.6 ?

& did you re-set/change all your apache settings to the CookBook App ?
(often when copying / restoring the permissions are set to root:root, which is wrong)

**Comment by mggcodes** [comment] 2020-12-16 12:45
Yes I installed CB0.7.6 and restore the folder and file permissions so that my apache server can access it.
The recipe.json file was created after saving but not all parameters was saved to this file.

saved file:
`{"id":"362665","name":"Hundekekse","description":"","url":"","image":"","prepTime":"PT0H0M","cookTime":"PT0H0M","totalTime":"PT0H0M","recipeCategory":"Hundeleckerchen","keywords":"","recipeYield":350,"recipeIngredient":[],"@context":"http:\/\/schema.org","@type":"Recipe","dateCreated":"0","dateModified":"1608105606","printImage":"false","imageUrl":"\/index.php\/apps\/cookbook\/recipes\/362665\/image?size=full","tool":[],"recipeInstructions":[]}`

expected result:
`{"id":"362665","name":"Hundekekse","description":"","url":"","image":"","prepTime":"PT0H0M","cookTime":"PT0H0M","totalTime":"PT0H0M","recipeCategory":"Hundeleckerchen","keywords":"","recipeYield":350,"recipeIngredient":["1 Ei", "250g Leberwurst","500g Haferflocken", "300g H\u00fcttenk\u00e4se", "100ml Sonnenblumen\u00f6"],"@context":"http:\/\/schema.org","@type":"Recipe","dateCreated":"0","dateModified":"1608105606","printImage":"false","imageUrl":"\/index.php\/apps\/cookbook\/recipes\/362665\/image?size=full","tool":[],"recipeInstructions":["Alle Zutaten in einer Sch\u00fcssel vermischen und ca. 1 Stunde im K\u00fchlschrank ziehen lassen.","Wenn der Teig danach noch zu nass zum Ausrollen ist, bitte noch mehr Haferflocken oder (Kartoffel-)Mehl zugeben. Anschliessend den Teig ca. 1 cm dick auf einer bemehlten Arbeitsfl\u00e4che ausrollen.", "Bei 150 Grad Umluft f\u00fcr ca. 30 Minuten backen und im ausgeschalteten Backofen gut durchtrocknen lassen."]}`

So the recipeInstructions and the recipeIngredient is empty. Maybe some problems with specialchars? (In german like ß.ä.ü.ö )
But before updating to CB:0.7.7 it worked correctly.

Is there any logfile? So I can have a look for some problems.

**Comment by cyberius0** [comment] 2020-12-16 22:39
Just installed Nextcloud 20.0.3 (snap) just because of the cookbook app(!) and it doesn't save the steps and ingredients as others said above. I installed the fix, even tried permissions 777.

**Comment by jotoeri** [comment] 2020-12-19 16:33
@christianlupus @mrzapp Are you planning to release this fixed version? Just as a patch? Version-Number got changed already, so it seems to be just one more step!? 🚀 😉

**Comment by Githopp192** [comment] 2020-12-20 09:52
@christianlupus .. so Christian you see .. your App became to be a Nextcloud Core App :-) 
One of the things people do beside saving files into the cloud is - cooking & eating & enjoying :-)

And yes .. i can say .. CookBook is one of my core Apps - because .. i like cooking .. i like eating. At the moment, i've got around 250 recipes .. but my goal is to have got more than 5000 !

So .. Christan and of all of you .. i wish Merry Christmas & againg Thanks Christian to your great work!
![ScreenShot1142](https://user-images.githubusercontent.com/32612067/102710238-46d5e680-42b1-11eb-9a7c-004e8ceb7226.jpg)

**Comment by danceswithcats** [comment] 2020-12-20 16:10
Hi all, this is one of my favourite apps, but stuck at the moment. Is the fix update likely to be soon? I'm not confident about using development versions. 
Anyway, happy Christmas.

**Comment by christianlupus** [comment] 2020-12-21 07:40
I was trying yesterday to push out a new release to the app store with the compatibility set accordingly. There is still an open issue #438 that needs to be tackled but at least currently NC 20 users can view their recipes again.

**Comment by thenamelessthing** [comment] 2021-01-04 03:54
Same thing for me! (since version 0.7.7)

**Comment by GambaJo** [comment] 2021-01-04 10:38
> 
> 
> I was trying yesterday to push out a new release to the app store with the compatibility set accordingly. There is still an open issue #438 that needs to be tackled but at least currently NC 20 users can view their recipes again.

#438 is closed. Is there a chance to deploy the fix now?

**Comment by nishantbb** [comment] 2021-01-06 22:04
Commenting to stay informed of the fix. I've been working around this for manual entries by importing a random recipe from a website (ex: allrecipes) and then editing from there. Thanks for a great app

**Comment by CSchaefer70** [comment] 2021-01-07 21:46
Same problem for me v20.0.4; Cookbook v0.7.7.  Spinning Wheel when "+ Create recipe".  Confirmed on Chrome, Firefox, Edge, Android.
![2021-01-07_16-41-58](https://user-images.githubusercontent.com/26978180/103948518-e398e080-5107-11eb-9eca-b95acd70f218.jpg)

**Comment by christianlupus** [comment] 2021-01-09 18:46
I pushed out version 0.7.8 just now. As the publication is working now, after updating to that version, the issues should be gone.

As currently there are multiple issues summed in this bug report, I assume I can close it. If further issues arise (might be the case), we can reopen here or if only loosely related, you can create a new issue.

**Closed by christianlupus** 2021-01-09 18:46 UTC
Labels: bug

**Comment by adriaaah** [comment] 2021-01-09 18:53
The release 0.7.8 fixed the issue and I can create/edit recipes like before the issue . Thank you!

**Comment by CSchaefer70** [comment] 2021-01-09 19:54
Just downloaded 0.7.8.  Lovely! Nice!

**Comment by nishantbb** [comment] 2021-01-09 23:32
Thank you!

**Comment by weinic** [comment] 2021-01-12 11:27
Thank you

Funktioniert auch unter NC 19 👍

**Comment by CSchaefer70** [comment] 2021-01-12 15:04
Ausser Sicht. Fantastisch. Ich habe NC19 übersprungen.

**Comment by CSchaefer70** [comment] 2021-01-12 15:07
Also, maybe I should post separately... an enhancement(?): When loading images currently limited to files within NC.  What about ability to go directly to camera or external URL?
 
![2021-01-12_9-56-53](https://user-images.githubusercontent.com/26978180/104331926-a5137500-54bd-11eb-8973-ecd73c7d0127.jpg)

**Comment by seyfeb** [comment] 2021-01-12 15:12
Right now it’s broken, but with PR #505 pasting an image URL should be working again

**Comment by GambaJo** [comment] 2021-01-15 18:50
@christianlupus Sorry, but I have still problems with this. Now I can click on the button to add ingredients, but when I save the recipe, the ingredients disappear.

**Comment by christianlupus** [comment] 2021-01-15 18:53
@GambaJo are you using the `master` branch? There was no update yet in the appstore.

**Comment by Moini** [comment] 2021-01-15 18:54
Same here. App is from FDroid.

**Comment by GambaJo** [comment] 2021-01-15 18:55
> 
> 
> @GambaJo are you using the `master` branch? There was no update yet in the appstore.

Ah ok, I use 0.7.8 from the nextcloud app store.

**Comment by christianlupus** [comment] 2021-01-15 22:02
@Moini @GambaJo you need to differentiate between the cookbook app for nextcloud (this repository) and the android app (F-Droid).
Our update to the NC app caused issued with the apps for mobiles as the API endpoints have changed. We are going to prevent that in the future but for now this can have happend.

**Comment by Moini** [comment] 2021-01-15 22:34
Yes, sorry, I got confused - there's a different bug in the app for Android, so it doesn't open any recipes any more that have been created with recent cookbook web app versions. I know this is a different tracker - and there was an update for Nextcloud, and it also updated cookbook. And since that update, one can add ingredients, but they don't show for all recipes.

**Comment by GambaJo** [comment] 2021-01-16 10:09
Ok, 0.7.9 seems to work. Will test this weekend.

**Comment by christianlupus** [comment] 2021-01-16 10:27
> [...] And since that update, one can add ingredients, but they don't show for all recipes - in the web app.

Do you mean for all or for any? So are there  some recipes where the app shows the ingredients and some it does not? Then, please open a new issue. If all recipes simply show no ingredients after manual adding them, it should be done in 0.7.9.

**Comment by Moini** [comment] 2021-02-01 02:28
It seems to work now, thank you! I've added those ingredients that were missing back in today.
