### ISSUE TITLE
Sectioned Ingredients

### ISSUE THREAD

**Issue by CiaranGruber** [nextcloud/cookbook#2526] opened 2024-10-03 09:08 UTC
**Is your feature request related to a problem? Please describe.**
I have a few recipes where it would be useful to have multiple sections for ingredients, something which is pretty common in some recipes, particularly ones where a sauce is related, but also when baking. You can see an example of this in [this cake recipe](https://www.taste.com.au/recipes/carrot-cake-3/58531339-dfb0-4596-838f-9113fa39c271?r=recipes/100bestcakerecipes&c=3wia69s9/100%20best%20cake%20recipes) with a separate section for icing or [this apple crumble recipe](https://www.taste.com.au/recipes/quick-easy-apple-crumble/4f2e1fb8-2060-4e27-9833-a5ab7ab69717) where there's a separate section for the crumble.

Example:
<img src="https://github.com/user-attachments/assets/6c46d300-e403-47c4-b0ab-c491042fc693" height="400" />

**Describe the solution you'd like**
It would be nice to be able to specify sections for ingredients, potentially via an Add Section button like seen in the mockup below. This functionality could also be expanded to the instructions potentially.

![Image](https://github.com/user-attachments/assets/4f52c9b8-fa4b-40aa-b1ff-8a00e85e6c19)

**Describe alternatives you've considered**
In some cases, it can be worth creating a separate recipe, such as when it's a sauce that could be used in multiple recipes, though if it's specific to the recipe (such as the Apple crumble), the best way of separating stuff is usually by adding something like (Apple) and (Crumble) at the end. That's more messy than having the potential for sections however

**Comment by christianlupus** [comment] 2024-10-03 14:45
There is currently something in place. 

You can add a line `## Dough` as an ingredient entry to get a heading. this is just a workaround, we plan to implement this for real. 

You can also link to other recipes if you reuse your self-made pumpkin spice in different other recipes. The syntax of this is somewhat verbose: `#r/1245` where 1245 is the recipe id (you find it in the URL when opening the recipe). There should be a modal dialog popping up once you type `#` but last time I tried, it did not work as expected. I think this was reported some time in the past.

**Comment by christianlupus** [comment] 2024-10-03 14:46
This is mostly a duplicate of #311. Closing here.

**Closed** 2024-10-03 14:47 UTC
Labels: enhancement
