### ISSUE TITLE
Sharing recipe with other users or external users

### ISSUE THREAD

**Issue by nodiaque** [nextcloud/cookbook#2577] opened 2024-11-14 21:13 UTC
Hello,

It would be great if there was a way to share recipe with other users (either per recipe or per cookbook) and allow both read only / full access to them for collaboration.

Allowing for read only guest would be a plus.

Thank you!

**Comment by nodiaque** [comment] 2024-11-15 16:57
Yeah you have the share the folder, not the best thing since cookbook require a base path to work, you then need everyone to use the same basepath to collaborate.

**Comment by benchti** [comment] 2024-11-24 21:43
hello  @nodiaque i think you could read this ticket https://github.com/nextcloud/cookbook/issues/120

**Comment by christianlupus** [comment] 2024-12-02 15:19
Duplicate of #120 and #392

**Closed by christianlupus** 2024-12-02 15:19 UTC
Labels: enhancement
