### ISSUE TITLE
Image uploads for each preparation step

### ISSUE THREAD

**Issue by HolgerHees** [nextcloud/cookbook#1041] opened 2022-06-13 06:51 UTC
Currently I try to convert all my recipes to cookbook. A lot of them, I can just refetch directly from chefkoch.de.

But a lot (~100) are just screenshots of old books collected during the last years. Currently there is no way. to attach this screenshots to a recipe.

It would be helpful if I can attach each screenshot to a cooking step in addition to this free text field.

**Comment by seyfeb** [comment] 2022-06-13 08:44
Duplicate of https://github.com/nextcloud/cookbook/issues/47

**Closed by seyfeb** 2022-06-13 08:44 UTC
Labels: enhancement
