### ISSUE TITLE
Trying to import recipe from an unsupported site makes app unreachable

### ISSUE THREAD

**Issue by sam-19** [nextcloud/cookbook#177] opened 2020-03-27 09:03 UTC
Hello. I tried to import a recipe from a local newspaper's website. Importing the recipe resulted in an error in the server admin log:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_cookbook_keywords` (`recipe_id`, `name`, `user_id`) VALUES(?, ?, ?)' with params [LONG_INTEGER, "A STRING CONTAINING LINK HEADERS AND JAVASCRIPT CALLS", "USER"]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1
```
So apparently the script incorrectly identified parts of the page header as recipe JSON data. Now this would not have been a big problem, but unfortunately the app saved this wrong data as a JSON object in my user's recipe folder. Now, when I tried to access the cookbook (just the index page) with this user, the app seems to try and automatically insert this unfinished recipe into the database, resulting in repeat errors in the server log, and the entire app becoming completely unusable (trying to open the app just gives the Nextcloud server error page). Clearing the browser cache or changing to another browser does not help. The problem only affected the user account that tried to import the recipe, other accounts worked fine. *Manually deleting the folder containing the malformed JSON corrected the problem*, but the regular end user might not easily find this solution.

If you want to reproduce, try to import the recipe from
https://www.hs.fi/ruoka/reseptit/art-2000006440950.html
but keep in mind that you probably have to locate and manually delete the recipe to regain access to the app.

**Comment by mrzapp** [comment] 2020-03-27 09:29
@sam-19 before this can be fixed, you can manually delete the recipe folder to prevent the database error

**Comment by mrzapp** [comment] 2020-05-05 10:39
@sam-19 if you like the website you linked to, you might want to inform them that their schema.org markup is all over the place. For instance, they've marked up the ingredients as `recipeInstructions`, and the word `recipeIngredient` doesn't even appear in the page's HTML.

**Comment by iluvatyr** [comment] 2022-05-20 13:02
Still having this issue with several recipees. nextcloud cookbook app inaccessible after adding one of those recipies.

https://www.hellofresh.de/recipes/gnocchi-in-cremesosze-mit-getrockneten-tomaten-61f0fc3792ce7c428d02da57
https://www.hellofresh.de/recipes/linguine-basilico-mit-spinat-und-hartkase-62713b1b68669b820d02893e

i think it shows an sql error while importing them, then they dont get shown in the cookbook and cookbook is accessible until nextcloud is restarted. Then on restart, there are internal errors when opening the app and it cannot be accessed anymore.

**Comment by christianlupus** [comment] 2022-05-21 08:19
I debugged it. There are two things to consider. First the recipe name might be too long as hellofresh puts some advertising there. I cut that in #1014.

Second, the page is using the wrong page encoding. Thus, nasty chars are inserted into the database. So, this sis fact also a duplicate of #284.

**Closed** 2022-05-21 09:04 UTC
Labels: bug, php, Backend
