### ISSUE TITLE
import of recipes not possible: could not fetch site

### ISSUE THREAD

**Issue by trajan66** [nextcloud/cookbook#320] opened 2020-09-20 10:10 UTC
Hello
recently I can no longer import recipes
error message "could not fetch site ... '(for example https://www.cuisineactuelle.fr/recettes/riz-biryani-a-l-indienne-206105)
debian 10.4
php 7.3.19
NC 18.09
thank you for your great app and for your help

**Browser**
Firefox 80

**Comment by christianlupus** [comment] 2020-09-22 13:02
I just tried it and found that the recipe url seems correct. On my first try to import the recipe it failed. But trying to debug further, I was no longer able to reproduce the issue.

@trajan66, could you try to import the URL once more. If it fails just retry once or twice. If it works, it looks like a (general) caching issue.

**Comment by christianlupus** [comment] 2020-11-07 16:28
No answer in more than a month. Closing here.

**Closed by christianlupus** 2020-11-07 16:28 UTC
Labels: bug, question
