### ISSUE TITLE
Locked out from NC 21.03 stuck on Cookbook update.

### ISSUE THREAD

**Issue by FreeJulianAssange** [nextcloud/cookbook#762] opened 2021-07-06 04:20 UTC
Hi,

I'm running a LAMP stack on Ubuntu 20.04.
NC 21.03 (Just upgraded from 20.03, then 20.09 (I think).
PHP 7.4

The 21.03 upgrade went smoothly, then the following day I got a notification that cookbook has an update.
However the update fails, and I am unable to log into NC via the web interface.

**sudo -u www-data php occ upgrade**

    Nextcloud or one of the apps require upgrade - only a limited number of commands are available
    You may use your browser or the occ upgrade command to do the upgrade
    Setting log level to debug
    Turned on maintenance mode
    Updating database schema
    Updated database
    Updating …
    **Exception: Database error when running migration latest for app cookbook**
    Update failed
    Maintenance mode is kept active
    Resetting log level

        
I'm a basic linux user so I'm not sure what else to try?

**Comment by christianlupus** [comment] 2021-07-06 05:34
Unfortunately, I am a bit short in time right now. Might be a duplicate of #754. I revoked the version on the app store until this is sorted out.

In the meantime to get your installation running again, you can do `occ app:disable cookbook`. I will come back later.

**Comment by the-impaler** [comment] 2021-07-06 08:04
Massive thanks for the app and all the work which has gone on with it.

Exactly the same issue here upon trying to update the app from 8.4 to 9.1. Same error messages at the terminal when trying to run `occ upgrade` and the same error message on the front end as #763. Used `occ app:disable cookbook` to get me back into my NC instance, then removed the cookbook 9.1 app from my install but it now won't reinstall, throwing the following error.

![Screen Shot 2021-07-06 at 09 00 24](https://user-images.githubusercontent.com/72580734/124564145-ac965400-de38-11eb-852f-37d2922a7b00.png)

Can I collect any info to help with the debugging process? I transferred ownership of the cookbook folder from one user to another, but haven't shared the folder with another user.

Which issue are we using to track this problem & resolution?

**Comment by poltrian** [comment] 2021-07-06 09:08
See #763 is Rob an existing user? One of my Users has left next cloud. The other user has left the cookbook group (is use Group folders)

**Comment by the-impaler** [comment] 2021-07-06 09:22
Version 8.4 reinstalled without issue.

@poltrian yes, "Rob" was an existing user and is the user account I was using to install the app (its another user in the administrator group).The Recipes folder was transferred from another user to "Rob".

Yes it does look like its a permissions issue, whether transferred ownership or shared ownership. I'm also no dev, but hopefully this info might help!

**Comment by christianlupus** [comment] 2021-07-06 09:45
It's a similar problem I guess. @the-impaler could you run [these SQL instructions](https://github.com/nextcloud/cookbook/issues/763#issuecomment-874525341) but with id 628989 to verify the same effect? I suspect there will be some recipes still in the cache from user Rob which will cause trouble.

It could be the case that the reinstallation removed the entries. Then you should be able to upgrade to 0.9.1 without issue.

**Comment by FreeJulianAssange** [comment] 2021-07-06 11:07
> In the meantime to get your installation running again, you can do `occ app:disable cookbook`.

Thanks for this command, as a newbie I was stuck, so this really saved me!

Let me know if I can provide any logs or further details.

**Closed** 2021-08-09 15:28 UTC
Labels: bug
