### ISSUE TITLE
Function that allows you to divide or multiply the list of ingredients

### ISSUE THREAD

**Issue by oxedgar** [nextcloud/cookbook#1551] opened 2023-03-20 18:43 UTC
Function that allows you to divide or multiply the list of ingredients according to the number of people desired.

Add a plus button and a minus button to add or subtract a person at the portion level. this way cooking will be even easier...

The data should however be saved as an array in the recipes and redisplayed with a split to make the calculations easier:
"quantity":"unit":"ingredient" for example "1.5";"egg":"pcs" or even "150";"ml";"milk"

Thank you for your valuable work to the community.

**Comment by christianlupus** [comment] 2023-03-20 19:43
Duplicate of #116.

**Closed** 2023-03-20 19:43 UTC
Labels: enhancement
