### ISSUE TITLE
Key 3 in ingredients will bring up a drop box

### ISSUE THREAD

**Issue by AlexWerz** [nextcloud/cookbook#710] opened 2021-05-04 16:12 UTC
**Description**
I am creating a new recipe and am adding the ingredients. Whenever I press the number 3 a popup with all my recipes pops up. I have no clue why or how to disable it.
I am using the german translation but the popup still says "select option".

**Reproduction**
1. Create a new recipe
2. Add an ingredient
3. In the textbox press '3'
4. A popup opens which says "select option"

**Expected behavior**
'3' ist added to the text of the textbox.

**Actual behavior**
a popup opens

**Screenshots**
![image](https://user-images.githubusercontent.com/8876196/117034942-180e5900-ad04-11eb-990e-eb389ef9ad28.png)

**Browser**
Chrome latest

**Versions**
Nextcloud server version: 21.0.1
Cookbook version: 0.8.4
Database system: PostgreSQL

**Comment by seyfeb** [comment] 2021-05-04 16:14
Duplicate of #670

**Closed by seyfeb** 2021-05-04 16:14 UTC
Labels: bug
