### ISSUE TITLE
No scroll bar on browser version

### ISSUE THREAD

**Issue by doom-freak** [nextcloud/cookbook#1298] opened 2022-10-29 11:05 UTC
Cookbook does not render with full recipe on the browser version.  Unable to scroll through the recipe.

Nextcloud Version: 25.0.0
Cookbook Version: 0.9.15
Workaround is to zoom out on the browser, but the text becomes very small.

I tried this on 
Safari: 16.1
Firefox for Mac: 106.0.1

**Comment by MarcelRobitaille** [comment] 2022-10-29 12:10
We do not yet support NC25. Duplicate of #1208. It's really a shame that Nextcloud does not have a better mechanism to warn users that not their apps will support NC25 before they update.

**Closed by MarcelRobitaille** 2022-10-29 12:10 UTC

**Comment by MarcelRobitaille** [comment] 2022-10-29 12:14
Please also check for existing issues before opening a new one. There have already been duplicates where users have reported inability to scroll.
