### ISSUE TITLE
Problem with encoding some recipes

### ISSUE THREAD

**Issue by bluszcz** [nextcloud/cookbook#459] opened 2020-12-24 20:22 UTC
**Description**

Problem with encoding after parsing some recipes urls.

**Reproduction**

1. Enter recipe url: https://kuchnialidla.pl/weganska-pasta-a-la-makrela
2. Click on '->'

**Expected behavior**

Recipe has correct encoding.

**Screenshots**

![image](https://user-images.githubusercontent.com/221943/103105391-d5d65c00-462d-11eb-961d-19ff7383b8ef.png)

![image](https://user-images.githubusercontent.com/221943/103105417-04543700-462e-11eb-931a-0dcd0bc78cbe.png)

**Browser**

Brave, chrome, firefox.

**Comment by teemue** [comment] 2021-01-06 15:01
Maybe related: when creating new recipe manually and data contains letters like ä, ö or å, the data will not be saved.

**Comment by seyfeb** [comment] 2021-01-06 15:11
@teemue I can’t confirm this on the current development version, so this might already be solved.

**Comment by Web-svg** [comment] 2021-01-10 11:49
Dear all,
Great improvment and many thanks to all of you!
Maybe identical or similar issue with app in 0.7.8 on NC 20.0.4.
Tags on top of the page are not correct (UTF-8 /conversion issue ?).
After importing  dumped recipes from cookido by using local URL related to the recipe from local web server ( UTF-8 encoded pages), localization appears with same behavior.
Original recipe :
![2021-01-10 12_17_30-Window](https://user-images.githubusercontent.com/63095113/104121778-2c87a980-5341-11eb-8ede-0bab0a2b3548.png)
Imported recipe :
![2021-01-10 12_02_04-Window](https://user-images.githubusercontent.com/63095113/104121768-209be780-5341-11eb-9092-4ec405aa717d.png)
Hope this help.

**Comment by bluszcz** [comment] 2021-03-21 15:01
It still does happen ( checked on the latest updated version from the store, i removed and reimported the recipe):
![image](https://user-images.githubusercontent.com/221943/111909712-aa151780-8a5e-11eb-8898-11e29c1eeb66.png)

**Comment by MarcelRobitaille** [comment] 2022-03-19 19:00
I think this is a duplicate of #284

**Closed by MarcelRobitaille** 2022-03-19 19:00 UTC
Labels: bug
