### ISSUE TITLE
Navigation button is hard to see

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1117] opened 2022-07-26 09:33 UTC
When looking at the current state of #1105, the navigation menu is reappearing again. See below:
![grafik](https://user-images.githubusercontent.com/8202922/180970587-71879960-5f47-426b-909f-cbdba8304b63.png)

When the navigation is expanded and the zoom factor is set correctly, the button might overlap with the edit (or other) button(s).

At least for me, this is almost invisible. I have seen this problem already in the past also with other apps on my mobile that the styling of the nav buttons might conflict with underlying content. Graphical example:

![grafik](https://user-images.githubusercontent.com/8202922/180970663-3cba3776-ecfc-44dd-b86d-5b7dd89b2e63.png)

I am not sure if this is really an app issue or better suited in the Nextcloud style guides (as other apps are affected similarly).

**Comment by MarcelRobitaille** [comment] 2022-07-26 21:06
I have noticed this as well. This is caused by `@nextcloud/vue` `AppNavigation`, and they don't provide a clean way to solve this IMO. I dislike many things about `AppNavigation` to be honest. I find they placement of the button over our own titlebar using `position: absolute` to be hacky. I think the close button should be inside the sidebar so that they can ensure good contrast and that it's not overlapping with the app's elements. I wish they would let us implement our own open button that we can position in a sane way using flexbox in our title bar and a close button that they position in a sane way in the sidebar.

</rant>

As for a workaround, we could put an overlay over the app when the sidebar is open. Another gripe about the `AppNavigation` is that there's no good way to know if it's open. They document how to open and close it using `event-bus`, but I was not able to subscribe to those events after reading through the `event-bus` docs. Maybe we could hack something together in css with a sibling selector on `app-navigation--close`. However, the sidebar has 4 states: widescreen shown, widescreen manually dismissed, narrow screen hidden, and narrow screen manually opened. The sibling selector would only detect if it's closed or not. Maybe we could use a media query as well, but then we would have a magic number that could be changed upstream.

**Comment by christianlupus** [comment] 2022-07-27 06:44
Yes, that is the issue. The problem lies in the Vue library, I see. This problem is only a minor issue at the moment. So, I would rather check for a solid solution before going into some hackery.

So, the question for @nextcloud/vuejs would be if a PR would be accepted/anticipated that will add emitting events to the `AppNavigation` component for showing/hiding the navigation component. If yes, I would suggest that we are forking the repo, add the code and create a PR.

**Comment by christianlupus** [comment] 2022-07-27 07:13
Well, I was able to tap into the event bus. I will send you a PR.

**Comment by MarcelRobitaille** [comment] 2022-07-27 07:19
Really? I just tested it again and I am not getting any events. Did you have to do anything special? I copied the same `subscribe` call as `AppNotification` and nothing.

**Comment by christianlupus** [comment] 2022-07-27 07:23
See https://github.com/christianlupus/nextcloud-cookbook/tree/test/event-bus-open-navigation

**Comment by MarcelRobitaille** [comment] 2022-07-27 07:46
What the heck. I was subscribing to `toggle-navigation`. I didn't notice that they were emitting `navigation-toggled` instead. Thanks!

**Comment by christianlupus** [comment] 2022-07-27 12:06
Yes, the same happened to me. The trick is that with `toggle-navigation` you can simulate a clock on the toggle button.

**Comment by seyfeb** [comment] 2022-07-27 12:10
There is a [vue-devtools](https://devtools.vuejs.org) browser plugin which should record emitted events and might help detecting the event names!

**Comment by MarcelRobitaille** [comment] 2022-07-27 12:14
The plugin has not been working reliably for me. Sometimes it shows up, but sometimes it doesn't recognize that it's a vue app.

**Comment by christianlupus** [comment] 2022-07-27 13:24
Yes and no. Firefox is not working ATM. Chrome works well, but you need to do some steps in the right order:
- Make sure the dev tools are closed.
- Make sure, you have a dev build and force-relaod (Ctrl + F5)
- Click on the Vue symbol. A message will appear that Vue is not detected. Wait 2~3 secs then confirm the message
- Open the dev tools
- Be patient, it takes 1~3 seconds until the Vue tab shows up.

The problem is that here, the event-bus is used instead of plain old Vue events. These events will not be detected by the Vue browser extension.

**Comment by seyfeb** [comment] 2022-07-27 15:31
Ah sorry then my comment was rather misleading 🙊

**Comment by MarcelRobitaille** [comment] 2022-07-28 06:39
Thanks for the instructions @christianlupus. I thought it would "just work". Not sure why it was sometimes working because I never did all of that. I am getting stuck on # 3 though. I don't have any confirm button, just the message "Vue.js is not detected". If I skip that step, I don't get any Vue tab.

**Closed** 2022-10-14 14:28 UTC
Labels: question, Frontend
