### ISSUE TITLE
Failed to getCategoryOfRecipe

### ISSUE THREAD

**Issue by florian-hild** [nextcloud/cookbook#498] opened 2021-01-11 15:06 UTC
**Nextcloud log**
```
{
  "reqId": "33Gnj3DDBaD0MzQxPYuO",
  "level": 3,
  "time": "2021-01-11T15:32:37+01:00",
  "remoteAddr": "192.168.0.53",
  "user": "admin",
  "app": "PHP",
  "method": "PUT",
  "url": "/apps/cookbook/api/recipes/108056",
  "message": {
    "Exception": "Error",
    "Message": "Trying to access array offset on value of type bool at /var/www/nextcloud/apps/cookbook/lib/Db/RecipeDb.php#503",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/cookbook/lib/Db/RecipeDb.php",
        "line": 503,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 173,
        "function": "getCategoryOfRecipe",
        "class": "OCA\\Cookbook\\Db\\RecipeDb",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 85,
        "function": "fetchDbAssociatedInformations",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 76,
        "function": "carryOutUpdate",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/cookbook/lib/Controller/RecipeController.php",
        "line": 95,
        "function": "addRecipe",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 169,
        "function": "update",
        "class": "OCA\\Cookbook\\Controller\\RecipeController",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 100,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 152,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 308,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 1008,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
    "Line": 91,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
  "version": "20.0.4.0"
}

```

**Expected behavior**
Nextcloud is freezing

**Screenshots**
<img width="293" alt="Screenshot 2021-01-11 at 15 59 10" src="https://user-images.githubusercontent.com/47560194/104198059-11db3080-5426-11eb-9475-8400164de924.png">

**Browser**
Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64)

**Note**
This is my first Bug report

**Comment by florian-hild** [comment] 2021-01-11 16:11
Duplicate of #494

**Comment by christianlupus** [comment] 2021-01-11 17:02
I am not sure if this is a duplicate of #494.
@florian-hild did you open one of the category entries on the left? Was the error log really caused by this issue? What is your version of the cookbook app?

**Closed** 2021-01-11 17:29 UTC
Labels: bug
