### ISSUE TITLE
How to add the weight of ingredients?如何添加食材的重量？

### ISSUE THREAD

**Issue by ShuiHuo** [nextcloud/cookbook#766] opened 2021-07-13 01:47 UTC
**Is your feature request related to a problem? Please describe.**
When adding ingredients, I need to add the weight and quantity of these ingredients and seasonings, but I can’t find the place to fill in. How do I fill in? 添加原料时我需要添加这些食材和调料的重量和份数，但我没找到填写位置，我该如何填写？

**Describe the solution you'd like**
I hope to add the place to fill in the weight and quantity. 我希望能添加填写重量和数量的地方。

![一张菜谱图片](https://user-images.githubusercontent.com/7471938/125376745-3fe20300-e3be-11eb-968c-254207cd1777.png)
![豆果上传菜谱页面 https://www.douguo.com/upfood.html](https://user-images.githubusercontent.com/7471938/125375797-43748a80-e3bc-11eb-9fdc-30cc5c87f07f.png)

**Comment by seyfeb** [comment] 2021-07-13 09:54
Hello ShuiHoo, those images you posted don’t ring a bell. Are you possibly posting this issue in the wrong repository? This is about the Nextcloud Cookbook app. If not, you can simply type the amount in your preferred unit in the text field, e.g., `200g red lentils`. I chose lentils because they’re supposed to be nutritious.

**Comment by ShuiHuo** [comment] 2021-07-13 10:15
@seyfeb  You may want to see this picture? 你可能是想看到这样的图片？ 
![2021-07-13_18-14-05](https://user-images.githubusercontent.com/7471938/125434839-0ff39818-a21c-42a0-bacd-cf997d38075a.png)


The picture initially sent is a picture of other recipe books and websites. I want Cookbook to have such an interface (function) to give cookbook some reference. 一开始发的图片是其他菜谱书籍和网站的图片，我想 cookbook 也有这样的界面（功能），能给 cookbook 一些参考。

Now the picture is the effect I have seen after two input labels, um ... a bit ugly ... 现在发的图片是我给网页加了两个 input 标签后看到的效果，嗯……有点丑……

**Comment by christianlupus** [comment] 2021-07-13 11:10
Duplicate of #116 in fact.

If not, please be more verbose about the difference to get your point across correctly. Thank you!

**Closed by christianlupus** 2021-07-13 11:10 UTC
Labels: enhancement
