### ISSUE TITLE
Integration of further recipe pages

### ISSUE THREAD

**Issue by Lukas2112** [nextcloud/cookbook#657] opened 2021-03-17 03:24 UTC
There are cooking and baking recipe sites, such as Sally's World. If it were possible to import these into Nextcloud Cookbook, it would be very cool.

**Comment by christianlupus** [comment] 2021-03-17 15:44
In general, the current state is to only import sites that support schema.org metadata. Without an example link, I cannot tell you if there is any sort of schema.org data involved in their site.

Apart from that, there was in the past the request to allow parsing of arbitrary sites. This is no trivial task though as it always is a hide-and-seek game with the website designers as *any* change on their site might break the parser. Please look at the older issues to find more information and continue there.

**Comment by Lukas2112** [comment] 2021-03-18 00:34
Okay, thank you very much for your consistent answer! But I have to say that the extension for Nextcloud was designed very intuitively.

**Comment by christianlupus** [comment] 2021-03-18 05:46
So, please send a link to an example recipe. If the page is sitting the schema this might be a big and can be addressed.
When no schema is provided, this issue is a duplicate and should be closed.

**Comment by Lukas2112** [comment] 2021-03-18 06:57
For example this: https://sallys-blog.de/vegane-mandelschnecken-nussschnecken

**Comment by christianlupus** [comment] 2021-03-18 11:57
I am sorry to inform you that that page is not publishing schema.org recipe data. Other data is published but no recipes. 

So, that makes it a duplicate of #217 and eventually others. Sorry.

**Closed by christianlupus** 2021-03-18 11:57 UTC
Labels: enhancement
