### ISSUE TITLE
[BUG] Nextcloud Log exploding when trying to add this recipe

### ISSUE THREAD

**Issue by florianwgnr** [nextcloud/cookbook#374] opened 2020-11-08 11:17 UTC
**Description**
I was trying to add the following recipe and it loaded longer than usual. After navigating to "/var/log/" i saw that "nextcloud.log" has increased to 8 GB! I cleared the log, refreshed the cookbook and tried it again. With an eye on the filesize it exploded again with an increase of 100 MB per second!

**Reproduction**
1. Add "https://www.chefkoch.de/rezepte/431091134310048/Gulasch-nach-Oma-Magda.html" or "https://www.chefkoch.de/rezepte/1254481230799966/Rotweinkuchen-schoen-saftig.html"
2. Click on the button to load it
3. Watch your Nextcloud Log explode within seconds

I dont know what the cause is and after 10 attempts the recipe loaded but there is a major bug in there.

**Screenshots**

Filesize after about 10 seconds of loading. The interersting part is, that my network speed is 0 so it is not downloading anything.

![grafik](https://user-images.githubusercontent.com/39341393/98463542-1b44e400-21bc-11eb-8ed6-686e83324726.png)

**Comment by christianlupus** [comment] 2020-11-08 11:49
Duplicate of #344

**Closed by christianlupus** 2020-11-08 11:49 UTC
Labels: bug

**Comment by christianlupus** [comment] 2020-11-08 11:50
A side remark: It might be a good idea to tell chefkoch about an invalig HTML structure. They might be able to solve the root case of the issue centrally.
