### ISSUE TITLE
Printing only prints first page

### ISSUE THREAD

**Issue by Smolders2007** [nextcloud/cookbook#1333] opened 2022-11-09 09:05 UTC
**Description**
When printing recipes , only the first page will show.

**Reproduction**
1. Go to any recipe that does not fit on a single page
3. Click on ...
4. Select print
5. Only one page will be printed

**Expected behavior**
All pages should print

**Actual behavior**
The print page shows a single page

**Browser**
Google Chrome
**Versions**
Nextcloud server version: 25.0.1
Cookbook version: 10.0
Database system: MySQL/MariaDB/PostgreSQL/Sqlite

**Comment by seyfeb** [comment] 2022-11-09 09:24
Duplicate of #1322

**Closed by seyfeb** 2022-11-09 09:24 UTC
Labels: bug
